### ISSUE TITLE
Update icu-dev package in ci and api Dockerfile

### ISSUE THREAD

**Issue by BacLuc** [ecamp/ecamp3#3246]
Upgrade the icu-dev package in
- [ ] ci (ubuntu)
- [ ] api/Dockerfile (alpine)

Alpine package: icu-dev https://pkgs.alpinelinux.org/package/edge/main/x86/icu-dev
(Probably only update to the latest alpine version needed.)
Ubuntu package: https://packages.ubuntu.com/jammy/libicu-dev

Needs to be icu version 72 or higher:
https://github.com/php/php-src/commit/8dd51b462d72bd3abeeb82f602a269e0b087b901
https://icu.unicode.org/

Cannot be done yet because the new package is not available in the ubuntu repositories yet.

**Comment by usu** [comment]
A potentiable solution: [https://github.com/shivammathur/setup-php](shivammathur/setup-php) is based on Ubuntu, but ships it's own builds for ICU. It's possible to specify which exact ICU version should be used, e.g.:

```
- name: Setup PHP with intl
  uses: shivammathur/setup-php@v2
  with:
    php-version: '8.1.13'
    extensions: intl-72.1
```

And ICU 72 is available in the builds:
https://github.com/shivammathur/icu-intl#icu4c-builds

Haven't tested. But according to the documentation, this should work
